name: build

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sectioncritical/avr-build
      credentials:
        username: kroesche
        password: ${{ secrets.CONTAINER_ACCESS }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: clean
        run: make -C build clean
      - name: build
        run: make -C build
      - name: check
        run: make -C build check
      - name: check-bloaty
        run: make -C build check-bloaty
      - name: changelog
        run: make -C build changelog VERSION=unreleased
      - name: package
        run: make -C build package VERSION=unreleased
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            build/zeva_bms_24-*.tar.gz
